// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramBotKit.Sample.PhotoSelector.Data;

#nullable disable

namespace TelegramBotKit.Sample.PhotoSelector.Data.Migrations
{
    [DbContext(typeof(PhotoSelectorDbContext))]
    partial class PhotoSelectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.BotUser", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GrantedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("TelegramUserId");

                    b.HasIndex("Role", "IsEnabled");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.BrowseSession", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrowseMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CurrentMediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoryMediaItemIds")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("BrowseSessions");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.MediaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IndexedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasMaxLength(127)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileUniqueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewFileId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewFileUniqueId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreviewIsReusable")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceSenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TelegramMessageDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceChatId", "SourceMessageId")
                        .IsUnique();

                    b.HasIndex("SourceChatId", "SourceThreadId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.Selection", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "MediaItemId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId", "State");

                    b.ToTable("Selections");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.SourceChat", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.HasIndex("IsEnabled");

                    b.ToTable("SourceChats");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.SourceTopic", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "ThreadId");

                    b.ToTable("SourceTopics");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.MediaItem", b =>
                {
                    b.HasOne("TelegramBotKit.Sample.PhotoSelector.Data.Entities.SourceChat", "SourceChat")
                        .WithMany("MediaItems")
                        .HasForeignKey("SourceChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceChat");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.Selection", b =>
                {
                    b.HasOne("TelegramBotKit.Sample.PhotoSelector.Data.Entities.MediaItem", "MediaItem")
                        .WithMany("Selections")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBotKit.Sample.PhotoSelector.Data.Entities.BotUser", "User")
                        .WithMany("Selections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.SourceTopic", b =>
                {
                    b.HasOne("TelegramBotKit.Sample.PhotoSelector.Data.Entities.SourceChat", "SourceChat")
                        .WithMany("Topics")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceChat");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.BotUser", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.MediaItem", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("TelegramBotKit.Sample.PhotoSelector.Data.Entities.SourceChat", b =>
                {
                    b.Navigation("MediaItems");

                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
