// <auto-generated/>
#nullable enable

// Polyfills required when targeting netstandard2.0 with newer C# features (records/init/module initializers).

namespace System.Runtime.CompilerServices
{
    // Required for 'record' and 'init' support on older TFMs.
    internal static class IsExternalInit { }

    // Required to allow the compiler to emit module initializers.
    [System.AttributeUsage(System.AttributeTargets.Method, Inherited = false)]
    internal sealed class ModuleInitializerAttribute : System.Attribute { }
}
